all: true

include:
  - library/src/*.js
exclude:
  - tests/
  - library/src/.internal

reporter:
  - text
  - lcov

report-dir: output/coverage
temp-dir: output/.nyc_output

check-coverage: true
instrument: true

branches: $(threshold)
lines: $(threshold)
functions: $(threshold)
statements: $(threshold)